---
# THis is referred to by ../.indentconfig.yaml because latexindent
# reads that be default, and only allows references to other configs in there.

# Awesome latex text wrap:
# https://github.com/cmhughes/latexindent.pl/issues/103#issuecomment-408630780
modifyLineBreaks:
  textWrapOptions:
    columns: 100
    perCodeBlockBasis: 0
    all: 1
    removeParagraphLineBreaks:
      all: 1
      beforeTextWrap: 1
  environments:
    BeginStartsOnOwnLine: 1
    BodyStartsOnOwnLine: 1
    EndStartsOnOwnLine: 1
    EndFinishesWithLineBreak: 1
    quote:
      BeginStartsOnOwnLine: 1
      BodyStartsOnOwnLine: 1
      EndStartsOnOwnLine: 1
      EndFinishesWithLineBreak: 1
    array:
      BeginStartsOnOwnLine: 0
      BodyStartsOnOwnLine: 1
      EndStartsOnOwnLine: 1
      EndFinishesWithLineBreak: 0
