---
# THis is referred to by ../.indentconfig.yaml because latexindent
# reads that be default, and only allows references to other configs in there.

# Use two spaces for indentation
defaultIndent: "  "
modifyLineBreaks:
  textWrapOptions:
    columns: 70
    unexpand: 0
    tabstop: 2
    perCodeBlockBasis: 1
    all: 1
    removeParagraphLineBreaks:
      all: 1
      beforeTextWrap: 1
  items:
    itemStartsOnOwnLine: 1
  environments:
    BeginStartsOnOwnLine: 1
    BodyStartsOnOwnLine: 1
    EndStartsOnOwnLine: 1
    EndFinishesWithLineBreak: 1
    quote:
      BeginStartsOnOwnLine: 4
      BodyStartsOnOwnLine: 1
      EndStartsOnOwnLine: 1
      EndFinishesWithLineBreak: 4
    array:
      BeginStartsOnOwnLine: 0
      BodyStartsOnOwnLine: 1
      EndStartsOnOwnLine: 1
      EndFinishesWithLineBreak: 0
